### ISSUE TITLE
File allocation implementation for Windows is problematic

### ISSUE THREAD

**Issue by nazar-pc** [al8n/fs4-rs#10]
While file allocation works on Windows, it is deeply problematic when actually trying to use the file later.

Specifically I tried allocating 500G file and then writing a piece of data at the end of the file. This resulted in everything related to that file freezing until the whole 500G is zeroed (presumably), which is definitely not what I expected and not how it behaves on Linux.

According to https://stackoverflow.com/a/25119897/3806795 the correct solution is to use `SetFilePointerEx` and then `SetEndOfFile`.

**Comment by al8n** [comment]
Thanks! I will take a look this weekend.

**Comment by nazar-pc** [comment]
I tried `SetFilePointerEx` with `SetEndOfFile` and the behavior is the same as current code of `fs4`. Not sure what to do with it now :confused:

**Comment by nazar-pc** [comment]
Posted a question on StackOverflow: https://stackoverflow.com/questions/78058306/how-to-pre-allocate-file-on-windows-ntfs-without-writing-the-whole-file

Closing for now since this doesn't seem to be an issue in fs4 necessarily.
