### ISSUE TITLE
Docs: Note Implicit Removal of Lock

### ISSUE THREAD

**Issue by goingforbrooke** [al8n/fs4-rs#18]
## Issue

The docs aren't clear not clear about how (locked) files are implicitly unlocked.

### Context

I had an error where two threads could acquire a lock on the same file. I was using `lock_subdirectory()` and `unlock_subdirectory()` with `try_lock_exclusive` and `unlock`, respectively.

The second function wasn't necessary because (judging from the behavior), there seems to be an implicit `unlock()` built into a `Drop` somewhere. I haven't been able to find it, though, so I'm open to being wrong about my interpretation.

## Solution

Documentation additions:
- lock files are implicitly unlocked when their file handle goes out of scope
- using `unlock()` isn't necessary

**Comment by al8n** [comment]
Hi, on Unix-like systems, file locks obtained using `flock` are automatically released when the file descriptor is closed or the process holding the lock exits. This automatic release of locks ensures that other processes can continue to access the file even if a process holding a lock terminates unexpectedly.
